#!/usr/bin/env bash

set -euo pipefail
# shellcheck source=./framework.sh
source "${BASE_DIR}/framework.sh"

quote="$(fortune "${quote_files[@]}" | fold -sw "${WIDTH}")"

print_columns "" "\n$CD${quote}$CN\n"

