#!/usr/bin/env bash

set -euo pipefail
# shellcheck source=./framework.sh
source "${BASE_DIR}/framework.sh"

intro_fonts=(
  bell
  big
  slant
  contessa
  computer
  cricket
  cybermedium
  jazmine
  rectangles
)
font=${intro_fonts[ $RANDOM % ${#intro_fonts[@]} ]}

intro=$(fortune intro | figlet -f "$font" | lolcat --force)
print_columns "" "${intro}"
