#!/usr/bin/env bash
set -euo pipefail
# shellcheck source=./framework.sh
source "${BASE_DIR}/framework.sh"

# bt_start "figlet+lolcat"
intro=$(target/debug/intro | lolcat --force-color)
# bt_end "figlet+lolcat"

# bt_start "intro print_columns"
print_columns "" "\n${intro}"
# bt_end "intro print_columns"

# bt_cleanup
