#!/usr/bin/env bash

set -euox pipefail
# shellcheck source=./framework.sh
source "${BASE_DIR}/framework.sh"

if [[ "$(uname -o)" = "Darwin" ]]; then
  # https://iboysoft.com/wiki/mac-uptime.html
  boottime=`sysctl -n kern.boottime | awk '{print $4}' | sed 's/,//g'`
  unixtime=`date +%s`
  timeAgo=$(($unixtime - $boottime))
  uptime=`awk -v time=$timeAgo 'BEGIN { seconds = time % 60; minutes = int(time / 60 % 60); hours = int(time / 60 / 60 % 24); days = int(time / 60 / 60 / 24); printf("%.0f days, %.0f hours, %.0f minutes, %.0f seconds", days, hours, minutes, seconds); exit }'`
else
  uptime=$(uptime -p | cut -d ' ' -f 2-)
fi

print_columns "Uptime" "${uptime}"
