#!/usr/bin/env bash
. "$BASE_DIR/bt.sh"                            # source bt.sh
bt_init                            # initialize

set -eo pipefail
# shellcheck source=./framework.sh
source "${BASE_DIR}/framework.sh"

print_columns "Memory" "$(target/debug/memory)"
