[package]
name = "updates"
version = "0.1.0"
edition = "2021"

[dependencies]
segment = { path = "../../crates/segment" }
anyhow = "1.0.90"
ratatui = "0.28.1"
tokio = { version = "1.41.0", features = ["full"] }
tracing = "0.1.40"
plist = "1.7.0"
os_info = "3.8.2"
semver = "1.0.23"
