[package]
name = "ip"
version = "0.1.0"
edition = "2021"

[dependencies]
segment = { path = "../../crates/segment" }
anyhow = "1.0.90"
ratatui = "0.28.1"
local-ip-address = "0.6.3"
tracing = "0.1.40"
