[package]
name = "load"
version = "0.1.0"
edition = "2021"

[dependencies]
segment = { path = "../../crates/segment" }
anyhow = "1.0.89"
ratatui = "0.28.1"
ansi_term = "0.12.1"
sysinfo = "0.30.12"
tracing = "0.1.40"
